cssd_wm:
  ros__parameters:
    dispenser_name: "cssd_workcell"
    ip_address: "127.0.0.1:3306"
    username: "malcomneo"
    password: "malcomneo"
    database_name: "inventory"
    RAWM1_inventory: ["basin"]
    RAWM2_inventory: ["instrument1","instrument2","instrument3"]

