cssd_wm:
  ros__parameters:
    dispenser_name_: "cssd_workcell"
    ip_address: "127.0.0.1:3306"
    username: "malcomneo"
    password: "malcomneo"
    database_name: "inventory"
    max_request_size: 4
    R2R_docking_distance_threshold: 100.00
    R2R_server_name: "/query_server_XB001"
    subworkcell1_inventory: ["basin"]
    subworkcell2_inventory: ["instrument1","instrument2","instrument3"]

